"""
DISASTER_DB schema inventory — single source of truth for table/column names.

Layered schemas:
  RAW, CLEAN, GEO, FEATURES, SERVING, AGENT

Writer table keys use ``{schema}.{table}`` (e.g. ``CLEAN.INCIDENTS``).
"""
from __future__ import annotations

import os
from typing import Final

# ── Schema names ──────────────────────────────────────────────────────────────

SCHEMA_RAW: Final = "RAW"
SCHEMA_CLEAN: Final = "CLEAN"
SCHEMA_GEO: Final = "GEO"
SCHEMA_FEATURES: Final = "FEATURES"
SCHEMA_SERVING: Final = "SERVING"
SCHEMA_AGENT: Final = "AGENT"

ALL_SCHEMAS: Final = (
    SCHEMA_RAW,
    SCHEMA_CLEAN,
    SCHEMA_GEO,
    SCHEMA_FEATURES,
    SCHEMA_SERVING,
    SCHEMA_AGENT,
)

# ── Column lists (order = INSERT column order) ────────────────────────────────

TABLE_COLUMNS: dict[str, list[str]] = {
    # RAW
    f"{SCHEMA_RAW}.RAW_INCIDENT_SUBMISSIONS": [
        "RAW_ID", "SUBMISSION_ID", "SOURCE", "RECEIVED_AT", "PAYLOAD",
        "_SOURCE_SYSTEM", "_INGESTED_AT",
    ],
    f"{SCHEMA_RAW}.RAW_VOICE_CALLS": [
        "RAW_ID", "CALL_ID", "TRANSCRIPT", "TRANSCRIPT_TOKENS", "MODEL",
        "RECEIVED_AT", "PAYLOAD", "_SOURCE_SYSTEM", "_INGESTED_AT",
    ],
    f"{SCHEMA_RAW}.RAW_DISPATCHES": [
        "RAW_ID", "RESPONDER_ID", "INCIDENT_ID", "DISPATCHED_AT", "DISTANCE_KM",
        "ETA_SECONDS", "SOLVER", "PAYLOAD", "_SOURCE_SYSTEM", "_INGESTED_AT",
    ],
    f"{SCHEMA_RAW}.RAW_RESPONDER_STATUS": [
        "RAW_ID", "RESPONDER_ID", "REPORTED_AT", "LAT", "LNG", "STATUS",
        "PAYLOAD", "_INGESTED_AT",
    ],
    f"{SCHEMA_RAW}.RAW_FEEDBACK": [
        "RAW_ID", "RECOMMENDATION_ID", "INCIDENT_ID", "RESPONDER_ID", "ACTION",
        "REASON", "OVERRIDE_PAYLOAD", "DECIDED_AT", "_INGESTED_AT",
    ],
    # CLEAN
    f"{SCHEMA_CLEAN}.INCIDENTS": [
        "INCIDENT_ID", "SUBMISSION_ID", "TIMESTAMP", "LAT", "LNG", "PRIORITY_SCORE",
        "STATUS", "USER_ID", "SEVERITY", "INCIDENT_DESCRIPTION", "SIM_RUN_ID",
        "FIRST_REPORTED_AT", "LAST_UPDATED_AT",
    ],
    f"{SCHEMA_CLEAN}.VICTIMS": [
        "INCIDENT_ID", "VICTIM_ORDINAL", "AGE_BAND", "VULNERABILITIES", "INJURIES",
        "CONSCIOUSNESS", "EXTRACTED_AT",
    ],
    f"{SCHEMA_CLEAN}.DISPATCHES": [
        "DISPATCH_ID", "RESPONDER_ID", "INCIDENT_ID", "DISPATCHED_AT", "DISTANCE_KM",
        "ETA_SECONDS", "SOLVER", "DECIDED_BY",
    ],
    f"{SCHEMA_CLEAN}.RESPONDERS": [
        "RESPONDER_ID", "CALLSIGN", "RESPONDER_TYPE", "STATUS", "LAT", "LNG",
        "LOCATION_DESCRIPTION", "CAPABILITIES", "ASSIGNED_INCIDENT_ID", "UPDATED_AT",
    ],
    f"{SCHEMA_CLEAN}.CLUSTERS": [
        "CLUSTER_ID", "LAT", "LNG", "LOCATION_DESCRIPTION", "PRIORITY_SCORE",
        "DEMAND_COUNT", "REQUIRED_CAPABILITIES", "PREFERRED_CAPABILITIES",
        "MEMBER_INCIDENT_IDS", "SOURCE", "CLUSTER_METHOD", "WINDOW_START", "WINDOW_END",
        "CREATED_AT",
    ],
    f"{SCHEMA_CLEAN}.ROAD_ACCESS_SNAPSHOTS": [
        "ROAD_ACCESS_ID", "SOURCE", "VERSION", "LOADED_AT", "FEATURE_COLLECTION",
        "FEATURE_COUNT", "HARD_AVOID_COUNT", "SOFT_PENALTY_COUNT", "STATUS_COUNTS",
        "PROVIDER", "AVOIDANCE_STRATEGY",
    ],
    f"{SCHEMA_CLEAN}.ROAD_ACCESS_FEATURES": [
        "FEATURE_ID", "ROAD_ACCESS_ID", "LABEL", "ROAD_STATUS", "CONFIDENCE",
        "GEOMETRY_TYPE", "GEOMETRY", "PROPERTIES", "CREATED_AT",
    ],
    # GEO
    f"{SCHEMA_GEO}.H3_INDEX": [
        "INCIDENT_ID", "LAT", "LNG", "H3_RES7", "H3_RES8", "H3_RES9", "INDEXED_AT",
    ],
    f"{SCHEMA_GEO}.SECTORS": [
        "SECTOR_ID", "NAME", "POLYGON", "CENTROID_LAT", "CENTROID_LNG",
    ],
    f"{SCHEMA_GEO}.ROUTE_COVERAGE": [
        "RESPONDER_ID", "INCIDENT_ID", "ROUTE_GEOM", "STARTED_AT", "ENDED_AT",
        "DISTANCE_KM", "H3_CELLS_RES8",
    ],
    # FEATURES
    f"{SCHEMA_FEATURES}.INCIDENT_MINUTE_COUNTS": [
        "MINUTE", "SEVERITY", "SECTOR_ID", "N",
    ],
    f"{SCHEMA_FEATURES}.SEVERITY_RATE_5MIN": [
        "BUCKET_END", "SECTOR_ID", "TOTAL_N", "IMMEDIATE_N", "IMMEDIATE_RATE",
    ],
    f"{SCHEMA_FEATURES}.RESOURCE_GAP": [
        "COMPUTED_AT", "SECTOR_ID", "OPEN_IMMEDIATE", "OPEN_DELAYED",
        "AVAILABLE_RESPONDERS", "GAP_SCORE",
    ],
    f"{SCHEMA_FEATURES}.FEEDBACK_FEATURES": [
        "RECOMMENDATION_ID", "INCIDENT_ID", "SEVERITY", "PRIORITY_SCORE",
        "PROPOSED_RESPONDER", "PROPOSED_ETA_S", "SECTOR_ID", "GAP_SCORE_AT_DECISION",
        "LABEL", "DECIDED_AT",
    ],
    # SERVING
    f"{SCHEMA_SERVING}.DISPATCH_RECOMMENDATIONS": [
        "RECOMMENDATION_ID", "INCIDENT_ID", "PROPOSED_RESPONDER", "PROPOSED_ETA_S",
        "DISTANCE_KM", "RATIONALE", "ALTERNATIVES", "STATUS", "CREATED_AT", "EXPIRES_AT",
    ],
    f"{SCHEMA_SERVING}.CORTEX_ALERTS": [
        "ALERT_ID", "ALERT_TYPE", "SEVERITY", "SECTOR_ID", "PAYLOAD", "MESSAGE",
        "DETECTED_AT", "ACKNOWLEDGED_AT", "ACKNOWLEDGED_BY",
    ],
    f"{SCHEMA_SERVING}.ROUTING_INPUTS": [
        "ROUTING_INPUT_ID", "CREATED_AT", "RESPONDERS", "INCIDENTS", "CLUSTERS",
        "ROAD_ACCESS", "ACCEPTED_ASSIGNMENTS", "ROUTE_STOP_LIMIT", "MAX_CANDIDATES",
    ],
    f"{SCHEMA_SERVING}.ROUTE_RECOMMENDATIONS": [
        "ROUTE_ID", "SOLVER", "CREATED_AT", "ELAPSED_MS", "INPUT_INCIDENT_IDS",
        "INPUT_CLUSTER_IDS", "INPUT_RESPONDER_IDS", "ACCEPTED_ASSIGNMENTS",
        "ROUTE_STOP_LIMIT", "MAX_CANDIDATES", "ROAD_ACCESS_ID", "ROAD_ACCESS_SUMMARY",
        "UNASSIGNED", "PAYLOAD", "SIM_RUN_ID",
    ],
    f"{SCHEMA_SERVING}.ROUTE_LEGS": [
        "ROUTE_ID", "LEG_ID", "SEQUENCE_INDEX", "RESPONDER_ID", "INCIDENT_ID",
        "TARGET_ID", "TARGET_TYPE", "FROM_LAT", "FROM_LNG", "FROM_LOCATION_DESCRIPTION",
        "TO_LAT", "TO_LNG", "TO_LOCATION_DESCRIPTION", "DISTANCE_KM", "ETA_SECONDS",
        "ARRIVAL_SECONDS", "MEMBER_INCIDENT_IDS", "ROUTE_GEOMETRY", "DEGRADED",
        "PROVIDER_STATUS", "WARNINGS", "ASSIGNMENT_REASON", "CREATED_AT",
    ],
    f"{SCHEMA_SERVING}.RESPONDER_DISPATCHES": [
        "DISPATCH_ID", "ROUTE_ID", "LEG_ID", "RESPONDER_ID", "INCIDENT_ID", "STARTED_BY",
        "STARTED_AT", "SOLVER", "DISTANCE_KM", "ETA_SECONDS", "LEG", "STATUS",
    ],
    f"{SCHEMA_SERVING}.RESPONDER_ARRIVALS": [
        "ASSIGNMENT_ID", "RESPONDER_ID", "CALLSIGN", "INCIDENT_ID", "CLUSTER_ID",
        "ARRIVAL_TIMESTAMP", "PING_LAT", "PING_LNG", "ACCURACY_M", "ROUTE_ID",
        "DETECTION_METHOD", "DISTANCE_M",
    ],
    f"{SCHEMA_SERVING}.RESPONDER_LOCATION_PINGS": [
        "PING_ID", "RESPONDER_ID", "LAT", "LNG", "ACCURACY_M", "TIMESTAMP",
        "SPEED_MPS", "HEADING", "ASSIGNED_INCIDENT_ID", "ROUTE_ID", "LEG_ID",
    ],
    # AGENT
    f"{SCHEMA_AGENT}.CHAT_SESSIONS": [
        "SESSION_ID", "SCOPE", "SCOPE_REF_ID", "OPENED_BY", "OPENED_AT", "CLOSED_AT", "TITLE",
    ],
    f"{SCHEMA_AGENT}.CHAT_MESSAGES": [
        "MESSAGE_ID", "SESSION_ID", "SEQ", "ROLE", "AGENT_NAME", "CONTENT",
        "TOOL_CALLS", "CITATIONS", "TOKENS", "CREATED_AT",
    ],
    f"{SCHEMA_AGENT}.ENRICHED_INCIDENT_REPORTS": [
        "INCIDENT_ID", "ENRICHED_TEXT", "SEVERITY", "SECTOR_ID", "STATUS",
        "VICTIM_COUNT", "H3_RES8", "TIMESTAMP", "EMBEDDING_MODEL", "UPDATED_AT",
    ],
    f"{SCHEMA_AGENT}.DISPATCH_DECISIONS": [
        "DECISION_ID", "RECOMMENDATION_ID", "INCIDENT_ID", "RESPONDER_USER_ID", "ACTION",
        "REASON", "OVERRIDE_PAYLOAD", "DECIDED_AT", "SESSION_ID",
    ],
    f"{SCHEMA_AGENT}.FEEDBACK_LABELS": [
        "LABEL_ID", "INCIDENT_ID", "RECOMMENDATION_ID", "LABEL_TYPE", "LABEL_VALUE",
        "NOTES", "LABELED_BY", "LABELED_AT",
    ],
    f"{SCHEMA_AGENT}.AGENT_RUNS": [
        "RUN_ID", "AGENT_NAME", "SESSION_ID", "INCIDENT_ID", "INPUT_PAYLOAD",
        "OUTPUT_PAYLOAD", "TOOL_CALLS", "CORTEX_SEARCH_HITS", "STARTED_AT", "ENDED_AT",
        "LATENCY_MS", "COST_USD", "ERROR",
    ],
}

# Tables the app writes at runtime (subset of full inventory).
WRITABLE_TABLES: Final = frozenset({
    f"{SCHEMA_RAW}.RAW_INCIDENT_SUBMISSIONS",
    f"{SCHEMA_RAW}.RAW_VOICE_CALLS",
    f"{SCHEMA_RAW}.RAW_DISPATCHES",
    f"{SCHEMA_RAW}.RAW_RESPONDER_STATUS",
    f"{SCHEMA_CLEAN}.INCIDENTS",
    f"{SCHEMA_CLEAN}.VICTIMS",
    f"{SCHEMA_CLEAN}.DISPATCHES",
    f"{SCHEMA_CLEAN}.RESPONDERS",
    f"{SCHEMA_SERVING}.CORTEX_ALERTS",
    f"{SCHEMA_SERVING}.ROUTING_INPUTS",
    f"{SCHEMA_SERVING}.ROUTE_RECOMMENDATIONS",
    f"{SCHEMA_SERVING}.ROUTE_LEGS",
    f"{SCHEMA_SERVING}.RESPONDER_DISPATCHES",
    f"{SCHEMA_SERVING}.RESPONDER_ARRIVALS",
    f"{SCHEMA_SERVING}.RESPONDER_LOCATION_PINGS",
})

# Smoke / init verification — one representative table per schema layer.
REQUIRED_TABLES_BY_SCHEMA: dict[str, list[str]] = {
    SCHEMA_RAW: ["RAW_INCIDENT_SUBMISSIONS", "RAW_VOICE_CALLS", "RAW_DISPATCHES"],
    SCHEMA_CLEAN: ["INCIDENTS", "VICTIMS", "RESPONDERS", "DISPATCHES"],
    SCHEMA_GEO: ["H3_INDEX", "SECTORS", "ROUTE_COVERAGE"],
    SCHEMA_FEATURES: ["INCIDENT_MINUTE_COUNTS", "SEVERITY_RATE_5MIN", "RESOURCE_GAP"],
    SCHEMA_SERVING: [
        "CORTEX_ALERTS", "ROUTE_RECOMMENDATIONS", "ROUTE_LEGS",
        "RESPONDER_DISPATCHES", "RESPONDER_ARRIVALS",
    ],
    SCHEMA_AGENT: ["CHAT_SESSIONS", "ENRICHED_INCIDENT_REPORTS", "AGENT_RUNS"],
}


def database_name() -> str:
    return os.environ.get("SNOWFLAKE_DATABASE", "DISASTER_DB")


def qualified_table(table_key: str) -> str:
    """``CLEAN.INCIDENTS`` → ``DISASTER_DB.CLEAN.INCIDENTS``."""
    schema, table = table_key.split(".", 1)
    return f"{database_name()}.{schema}.{table}"


def parse_table_key(table_key: str) -> tuple[str, str]:
    schema, table = table_key.split(".", 1)
    return schema, table
