-- DISASTER_DB layered schema (Hilo Dispatch).
-- Idempotent: safe to run repeatedly.
--
--   uv run python scripts/snowflake_smoke.py --init
--
-- Column names match src/disaster/snowflake/tables.py (TABLE_COLUMNS).

CREATE DATABASE IF NOT EXISTS DISASTER_DB;

CREATE SCHEMA IF NOT EXISTS DISASTER_DB.RAW;
CREATE SCHEMA IF NOT EXISTS DISASTER_DB.CLEAN;
CREATE SCHEMA IF NOT EXISTS DISASTER_DB.GEO;
CREATE SCHEMA IF NOT EXISTS DISASTER_DB.FEATURES;
CREATE SCHEMA IF NOT EXISTS DISASTER_DB.SERVING;
CREATE SCHEMA IF NOT EXISTS DISASTER_DB.AGENT;

USE DATABASE DISASTER_DB;

-- Rebuild derived live dynamic tables when their definitions change.
-- Drop dependents first, then recreate in the normal init order below.
DROP DYNAMIC TABLE IF EXISTS DISASTER_DB.SERVING.LIVE_RESOURCE_GAPS;
DROP DYNAMIC TABLE IF EXISTS DISASTER_DB.FEATURES.LIVE_H3_CLUSTER_WINDOWS;

-- ═══════════════════════════════════════════════════════════════════════════
-- RAW
-- ═══════════════════════════════════════════════════════════════════════════
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW_INCIDENT_SUBMISSIONS (
    RAW_ID              VARCHAR(36)     NOT NULL,
    SUBMISSION_ID       VARCHAR(64)     NOT NULL,
    SOURCE              VARCHAR(32)     NOT NULL,
    RECEIVED_AT         TIMESTAMP_TZ    NOT NULL,
    PAYLOAD             VARIANT         NOT NULL,
    _SOURCE_SYSTEM      VARCHAR(64)     DEFAULT 'hilo_dispatch',
    _INGESTED_AT        TIMESTAMP_TZ    DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_VOICE_CALLS (
    RAW_ID              VARCHAR(36)     NOT NULL,
    CALL_ID             VARCHAR(64)     NOT NULL,
    TRANSCRIPT          VARCHAR(16777216),
    TRANSCRIPT_TOKENS   NUMBER,
    MODEL               VARCHAR(64),
    RECEIVED_AT         TIMESTAMP_TZ    NOT NULL,
    PAYLOAD             VARIANT,
    _SOURCE_SYSTEM      VARCHAR(64)     DEFAULT 'hilo_dispatch',
    _INGESTED_AT        TIMESTAMP_TZ    DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_DISPATCHES (
    RAW_ID              VARCHAR(36)     NOT NULL,
    RESPONDER_ID        VARCHAR(36)     NOT NULL,
    INCIDENT_ID         VARCHAR(36)     NOT NULL,
    DISPATCHED_AT       TIMESTAMP_TZ    NOT NULL,
    DISTANCE_KM         FLOAT,
    ETA_SECONDS         FLOAT,
    SOLVER              VARCHAR(40),
    PAYLOAD             VARIANT,
    _SOURCE_SYSTEM      VARCHAR(64)     DEFAULT 'hilo_dispatch',
    _INGESTED_AT        TIMESTAMP_TZ    DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_RESPONDER_STATUS (
    RAW_ID              VARCHAR(36)     NOT NULL,
    RESPONDER_ID        VARCHAR(36)     NOT NULL,
    REPORTED_AT         TIMESTAMP_TZ    NOT NULL,
    LAT                 FLOAT           NOT NULL,
    LNG                 FLOAT           NOT NULL,
    STATUS              VARCHAR(32)     NOT NULL,
    PAYLOAD             VARIANT,
    _INGESTED_AT        TIMESTAMP_TZ    DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_FEEDBACK (
    RAW_ID              VARCHAR(36)     NOT NULL,
    RECOMMENDATION_ID   VARCHAR(64),
    INCIDENT_ID         VARCHAR(36),
    RESPONDER_ID        VARCHAR(36),
    ACTION              VARCHAR(32)     NOT NULL,
    REASON              VARCHAR(500),
    OVERRIDE_PAYLOAD    VARIANT,
    DECIDED_AT          TIMESTAMP_TZ    NOT NULL,
    _INGESTED_AT        TIMESTAMP_TZ    DEFAULT CURRENT_TIMESTAMP()
);

-- ═══════════════════════════════════════════════════════════════════════════
-- CLEAN
-- ═══════════════════════════════════════════════════════════════════════════
USE SCHEMA CLEAN;

CREATE TABLE IF NOT EXISTS INCIDENTS (
    INCIDENT_ID          VARCHAR(36)     NOT NULL,
    SUBMISSION_ID        VARCHAR(64)     NOT NULL,
    TIMESTAMP            TIMESTAMP_TZ    NOT NULL,
    LAT                  FLOAT           NOT NULL,
    LNG                  FLOAT           NOT NULL,
    PRIORITY_SCORE       FLOAT           NOT NULL,
    STATUS               VARCHAR(32)     NOT NULL,
    USER_ID              VARCHAR(64),
    SEVERITY             VARCHAR(20)     NOT NULL,
    INCIDENT_DESCRIPTION VARCHAR(500)    NOT NULL,
    SIM_RUN_ID           VARCHAR(64),
    FIRST_REPORTED_AT    TIMESTAMP_TZ    NOT NULL,
    LAST_UPDATED_AT      TIMESTAMP_TZ    NOT NULL
);

CREATE TABLE IF NOT EXISTS VICTIMS (
    INCIDENT_ID         VARCHAR(36)     NOT NULL,
    VICTIM_ORDINAL      NUMBER          NOT NULL,
    AGE_BAND            VARCHAR(32),
    VULNERABILITIES     ARRAY,
    INJURIES            ARRAY,
    CONSCIOUSNESS       VARCHAR(32),
    EXTRACTED_AT        TIMESTAMP_TZ    NOT NULL
);

CREATE TABLE IF NOT EXISTS DISPATCHES (
    DISPATCH_ID         VARCHAR(36)     NOT NULL,
    RESPONDER_ID        VARCHAR(36)     NOT NULL,
    INCIDENT_ID         VARCHAR(36)     NOT NULL,
    DISPATCHED_AT       TIMESTAMP_TZ    NOT NULL,
    DISTANCE_KM         FLOAT,
    ETA_SECONDS         FLOAT,
    SOLVER              VARCHAR(40),
    DECIDED_BY          VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS RESPONDERS (
    RESPONDER_ID        VARCHAR(36)     NOT NULL,
    CALLSIGN            VARCHAR(40)     NOT NULL,
    RESPONDER_TYPE      VARCHAR(32)     NOT NULL,
    STATUS              VARCHAR(32)     NOT NULL,
    LAT                 FLOAT           NOT NULL,
    LNG                 FLOAT           NOT NULL,
    LOCATION_DESCRIPTION VARCHAR(500),
    CAPABILITIES        VARCHAR(1000),
    ASSIGNED_INCIDENT_ID VARCHAR(36),
    UPDATED_AT          TIMESTAMP_TZ    NOT NULL
);

CREATE TABLE IF NOT EXISTS CLUSTERS (
    CLUSTER_ID          VARCHAR(64)     NOT NULL,
    LAT                 FLOAT           NOT NULL,
    LNG                 FLOAT           NOT NULL,
    LOCATION_DESCRIPTION VARCHAR(500),
    PRIORITY_SCORE      FLOAT,
    DEMAND_COUNT        NUMBER,
    REQUIRED_CAPABILITIES VARCHAR(1000),
    PREFERRED_CAPABILITIES VARCHAR(1000),
    MEMBER_INCIDENT_IDS VARIANT,
    SOURCE              VARCHAR(32),
    CLUSTER_METHOD      VARCHAR(64),
    WINDOW_START        TIMESTAMP_TZ,
    WINDOW_END          TIMESTAMP_TZ,
    CREATED_AT          TIMESTAMP_TZ    NOT NULL
);

CREATE TABLE IF NOT EXISTS ROAD_ACCESS_SNAPSHOTS (
    ROAD_ACCESS_ID      VARCHAR(64)     NOT NULL,
    SOURCE              VARCHAR(64),
    VERSION             VARCHAR(32),
    LOADED_AT           TIMESTAMP_TZ    NOT NULL,
    FEATURE_COLLECTION  VARIANT,
    FEATURE_COUNT       NUMBER,
    HARD_AVOID_COUNT    NUMBER,
    SOFT_PENALTY_COUNT  NUMBER,
    STATUS_COUNTS       VARIANT,
    PROVIDER            VARCHAR(64),
    AVOIDANCE_STRATEGY  VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS ROAD_ACCESS_FEATURES (
    FEATURE_ID          VARCHAR(64)     NOT NULL,
    ROAD_ACCESS_ID      VARCHAR(64)     NOT NULL,
    LABEL               VARCHAR(256),
    ROAD_STATUS         VARCHAR(32),
    CONFIDENCE          FLOAT,
    GEOMETRY_TYPE       VARCHAR(32),
    GEOMETRY            VARIANT,
    PROPERTIES          VARIANT,
    CREATED_AT          TIMESTAMP_TZ    NOT NULL
);

-- ═══════════════════════════════════════════════════════════════════════════
-- GEO
-- ═══════════════════════════════════════════════════════════════════════════
USE SCHEMA GEO;

CREATE TABLE IF NOT EXISTS H3_INDEX (
    INCIDENT_ID         VARCHAR(36)     NOT NULL,
    LAT                 FLOAT           NOT NULL,
    LNG                 FLOAT           NOT NULL,
    H3_RES7             VARCHAR(32),
    H3_RES8             VARCHAR(32),
    H3_RES9             VARCHAR(32),
    INDEXED_AT          TIMESTAMP_TZ    NOT NULL
);

CREATE TABLE IF NOT EXISTS SECTORS (
    SECTOR_ID           VARCHAR(64)     NOT NULL,
    NAME                VARCHAR(128)    NOT NULL,
    POLYGON             VARIANT,
    CENTROID_LAT        FLOAT,
    CENTROID_LNG        FLOAT
);

CREATE TABLE IF NOT EXISTS ROUTE_COVERAGE (
    RESPONDER_ID        VARCHAR(36)     NOT NULL,
    INCIDENT_ID         VARCHAR(36)     NOT NULL,
    ROUTE_GEOM          VARIANT,
    STARTED_AT          TIMESTAMP_TZ,
    ENDED_AT            TIMESTAMP_TZ,
    DISTANCE_KM         FLOAT,
    H3_CELLS_RES8       VARIANT
);

CREATE DYNAMIC TABLE IF NOT EXISTS LIVE_INCIDENT_H3
    TARGET_LAG = '1 minute'
    WAREHOUSE = {{SNOWFLAKE_WAREHOUSE}}
    CLUSTER BY (H3_RES8, SECTOR_ID, INCIDENT_MINUTE)
AS
SELECT
    INCIDENT_ID,
    DATE_TRUNC('minute', TIMESTAMP) AS INCIDENT_MINUTE,
    TIMESTAMP AS INCIDENT_TIMESTAMP,
    LAT,
    LNG,
    TO_VARCHAR(H3_LATLNG_TO_CELL(LAT, LNG, 8)) AS H3_RES8,
    CASE
        WHEN LAT > 35.61 THEN 'NORTH'
        WHEN LAT < 35.57 THEN 'SOUTH'
        ELSE 'CENTRAL'
    END AS SECTOR_ID,
    SEVERITY,
    STATUS,
    PRIORITY_SCORE,
    SIM_RUN_ID,
    LAST_UPDATED_AT
FROM DISASTER_DB.CLEAN.INCIDENTS
WHERE LAT IS NOT NULL
  AND LNG IS NOT NULL;

-- ═══════════════════════════════════════════════════════════════════════════
-- FEATURES (populated by Snowflake tasks / dynamic tables in production)
-- ═══════════════════════════════════════════════════════════════════════════
USE SCHEMA FEATURES;

CREATE TABLE IF NOT EXISTS INCIDENT_MINUTE_COUNTS (
    MINUTE              TIMESTAMP_TZ    NOT NULL,
    SEVERITY            VARCHAR(20)     NOT NULL,
    SECTOR_ID           VARCHAR(64),
    N                   NUMBER          NOT NULL
);

CREATE TABLE IF NOT EXISTS SEVERITY_RATE_5MIN (
    BUCKET_END          TIMESTAMP_TZ    NOT NULL,
    SECTOR_ID           VARCHAR(64),
    TOTAL_N             NUMBER,
    IMMEDIATE_N         NUMBER,
    IMMEDIATE_RATE      FLOAT
);

CREATE TABLE IF NOT EXISTS RESOURCE_GAP (
    COMPUTED_AT         TIMESTAMP_TZ    NOT NULL,
    SECTOR_ID           VARCHAR(64),
    OPEN_IMMEDIATE      NUMBER,
    OPEN_DELAYED        NUMBER,
    AVAILABLE_RESPONDERS NUMBER,
    GAP_SCORE           FLOAT
);

CREATE TABLE IF NOT EXISTS FEEDBACK_FEATURES (
    RECOMMENDATION_ID   VARCHAR(64),
    INCIDENT_ID         VARCHAR(36),
    SEVERITY            VARCHAR(20),
    PRIORITY_SCORE      FLOAT,
    PROPOSED_RESPONDER  VARCHAR(36),
    PROPOSED_ETA_S      FLOAT,
    SECTOR_ID           VARCHAR(64),
    GAP_SCORE_AT_DECISION FLOAT,
    LABEL               VARCHAR(32),
    DECIDED_AT          TIMESTAMP_TZ
);

CREATE DYNAMIC TABLE IF NOT EXISTS LIVE_H3_CLUSTER_WINDOWS
    TARGET_LAG = '1 minute'
    WAREHOUSE = {{SNOWFLAKE_WAREHOUSE}}
    CLUSTER BY (H3_RES8, SECTOR_ID, WINDOW_END)
AS
SELECT
    CONCAT(H3_RES8, ':', SECTOR_ID) AS CLUSTER_WINDOW_ID,
    H3_RES8,
    SECTOR_ID,
    MIN(INCIDENT_MINUTE) AS WINDOW_START,
    MAX(INCIDENT_MINUTE) AS WINDOW_END,
    COUNT(*) AS OPEN_INCIDENTS,
    COUNT_IF(STATUS IN ('new', 'dispatched', 'en_route', 'partial')) AS ACTIVE_INCIDENTS,
    COUNT_IF(SEVERITY = 'Immediate') AS IMMEDIATE_COUNT,
    COUNT_IF(SEVERITY = 'Delayed') AS DELAYED_COUNT,
    COUNT_IF(SEVERITY = 'Minor') AS MINOR_COUNT,
    MAX(PRIORITY_SCORE) AS MAX_PRIORITY_SCORE,
    AVG(PRIORITY_SCORE) AS AVG_PRIORITY_SCORE,
    LISTAGG(INCIDENT_ID, ',') WITHIN GROUP (ORDER BY PRIORITY_SCORE DESC) AS INCIDENT_IDS
FROM DISASTER_DB.GEO.LIVE_INCIDENT_H3
WHERE STATUS IN ('new', 'dispatched', 'en_route', 'partial')
GROUP BY H3_RES8, SECTOR_ID;

CREATE DYNAMIC TABLE IF NOT EXISTS LIVE_ROUTE_STATUS
    TARGET_LAG = '1 minute'
    WAREHOUSE = {{SNOWFLAKE_WAREHOUSE}}
    CLUSTER BY (ROUTE_ID, RESPONDER_ID, LAST_EVENT_AT)
AS
WITH latest_dispatch AS (
    SELECT
        ROUTE_ID,
        LEG_ID,
        RESPONDER_ID,
        INCIDENT_ID,
        STATUS AS DISPATCH_STATUS,
        STARTED_AT,
        ETA_SECONDS
    FROM DISASTER_DB.SERVING.RESPONDER_DISPATCHES
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY RESPONDER_ID, COALESCE(ROUTE_ID, ''), COALESCE(LEG_ID, '')
        ORDER BY STARTED_AT DESC
    ) = 1
),
latest_ping AS (
    SELECT
        RESPONDER_ID,
        ROUTE_ID,
        LEG_ID,
        LAT,
        LNG,
        TIMESTAMP AS LAST_PING_AT
    FROM DISASTER_DB.SERVING.RESPONDER_LOCATION_PINGS
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY RESPONDER_ID, COALESCE(ROUTE_ID, ''), COALESCE(LEG_ID, '')
        ORDER BY TIMESTAMP DESC
    ) = 1
)
SELECT
    COALESCE(latest_dispatch.ROUTE_ID, latest_ping.ROUTE_ID) AS ROUTE_ID,
    COALESCE(latest_dispatch.LEG_ID, latest_ping.LEG_ID) AS LEG_ID,
    COALESCE(latest_dispatch.RESPONDER_ID, latest_ping.RESPONDER_ID) AS RESPONDER_ID,
    latest_dispatch.INCIDENT_ID,
    latest_dispatch.DISPATCH_STATUS,
    latest_dispatch.STARTED_AT,
    latest_dispatch.ETA_SECONDS,
    latest_ping.LAT AS LAST_LAT,
    latest_ping.LNG AS LAST_LNG,
    latest_ping.LAST_PING_AT,
    COALESCE(latest_ping.LAST_PING_AT, latest_dispatch.STARTED_AT) AS LAST_EVENT_AT,
    DATEDIFF(
        second,
        latest_dispatch.STARTED_AT,
        COALESCE(latest_ping.LAST_PING_AT, latest_dispatch.STARTED_AT)
    ) AS AGE_SECONDS
FROM latest_dispatch
FULL OUTER JOIN latest_ping
  ON latest_dispatch.RESPONDER_ID = latest_ping.RESPONDER_ID
 AND COALESCE(latest_dispatch.ROUTE_ID, '') = COALESCE(latest_ping.ROUTE_ID, '')
 AND COALESCE(latest_dispatch.LEG_ID, '') = COALESCE(latest_ping.LEG_ID, '');

-- ═══════════════════════════════════════════════════════════════════════════
-- SERVING
-- ═══════════════════════════════════════════════════════════════════════════
USE SCHEMA SERVING;

CREATE TABLE IF NOT EXISTS DISPATCH_RECOMMENDATIONS (
    RECOMMENDATION_ID   VARCHAR(64)     NOT NULL,
    INCIDENT_ID         VARCHAR(36)     NOT NULL,
    PROPOSED_RESPONDER  VARCHAR(36),
    PROPOSED_ETA_S      FLOAT,
    DISTANCE_KM         FLOAT,
    RATIONALE           VARCHAR(2000),
    ALTERNATIVES        VARIANT,
    STATUS              VARCHAR(32),
    CREATED_AT          TIMESTAMP_TZ    NOT NULL,
    EXPIRES_AT          TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS CORTEX_ALERTS (
    ALERT_ID            VARCHAR(36)     NOT NULL,
    ALERT_TYPE          VARCHAR(40)     NOT NULL,
    SEVERITY            VARCHAR(40)     NOT NULL,
    SECTOR_ID           VARCHAR(64),
    PAYLOAD             VARIANT,
    MESSAGE             VARCHAR(500)    NOT NULL,
    DETECTED_AT         TIMESTAMP_TZ    NOT NULL,
    ACKNOWLEDGED_AT     TIMESTAMP_TZ,
    ACKNOWLEDGED_BY     VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS ROUTING_INPUTS (
    ROUTING_INPUT_ID    VARCHAR(64)     NOT NULL,
    CREATED_AT          TIMESTAMP_TZ    NOT NULL,
    RESPONDERS          VARIANT,
    INCIDENTS           VARIANT,
    CLUSTERS            VARIANT,
    ROAD_ACCESS         VARIANT,
    ACCEPTED_ASSIGNMENTS VARIANT,
    ROUTE_STOP_LIMIT    NUMBER,
    MAX_CANDIDATES      NUMBER
);

CREATE TABLE IF NOT EXISTS ROUTE_RECOMMENDATIONS (
    ROUTE_ID            VARCHAR(64)     NOT NULL,
    SOLVER              VARCHAR(40)     NOT NULL,
    CREATED_AT          TIMESTAMP_TZ    NOT NULL,
    ELAPSED_MS          NUMBER,
    INPUT_INCIDENT_IDS  VARIANT,
    INPUT_CLUSTER_IDS   VARIANT,
    INPUT_RESPONDER_IDS VARIANT,
    ACCEPTED_ASSIGNMENTS VARIANT,
    ROUTE_STOP_LIMIT    NUMBER,
    MAX_CANDIDATES      NUMBER,
    ROAD_ACCESS_ID      VARCHAR(64),
    ROAD_ACCESS_SUMMARY VARIANT,
    UNASSIGNED          VARIANT,
    PAYLOAD             VARIANT,
    SIM_RUN_ID          VARCHAR(64)
);
-- Idempotent column add for environments where the table already exists.
ALTER TABLE ROUTE_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS SIM_RUN_ID VARCHAR(64);

CREATE TABLE IF NOT EXISTS ROUTE_LEGS (
    ROUTE_ID            VARCHAR(64)     NOT NULL,
    LEG_ID              VARCHAR(128)    NOT NULL,
    SEQUENCE_INDEX      NUMBER          NOT NULL,
    RESPONDER_ID        VARCHAR(36)     NOT NULL,
    INCIDENT_ID         VARCHAR(36),
    TARGET_ID           VARCHAR(64),
    TARGET_TYPE         VARCHAR(32),
    FROM_LAT            FLOAT,
    FROM_LNG            FLOAT,
    FROM_LOCATION_DESCRIPTION VARCHAR(500),
    TO_LAT              FLOAT,
    TO_LNG              FLOAT,
    TO_LOCATION_DESCRIPTION VARCHAR(500),
    DISTANCE_KM         FLOAT,
    ETA_SECONDS         FLOAT,
    ARRIVAL_SECONDS     FLOAT,
    MEMBER_INCIDENT_IDS VARIANT,
    ROUTE_GEOMETRY      VARIANT,
    DEGRADED            BOOLEAN,
    PROVIDER_STATUS     VARCHAR(64),
    WARNINGS            VARIANT,
    ASSIGNMENT_REASON   VARCHAR(500),
    CREATED_AT          TIMESTAMP_TZ    NOT NULL
);

CREATE TABLE IF NOT EXISTS RESPONDER_DISPATCHES (
    DISPATCH_ID         VARCHAR(36)     NOT NULL,
    ROUTE_ID            VARCHAR(64),
    LEG_ID              VARCHAR(128),
    RESPONDER_ID        VARCHAR(36)     NOT NULL,
    INCIDENT_ID         VARCHAR(36)     NOT NULL,
    STARTED_BY          VARCHAR(64),
    STARTED_AT          TIMESTAMP_TZ    NOT NULL,
    SOLVER              VARCHAR(40),
    DISTANCE_KM         FLOAT,
    ETA_SECONDS         FLOAT,
    LEG                 VARIANT,
    STATUS              VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS RESPONDER_ARRIVALS (
    ASSIGNMENT_ID       VARCHAR(64)     NOT NULL,
    RESPONDER_ID        VARCHAR(36)     NOT NULL,
    CALLSIGN            VARCHAR(40)     NOT NULL,
    INCIDENT_ID         VARCHAR(36)     NOT NULL,
    CLUSTER_ID          VARCHAR(120),
    ARRIVAL_TIMESTAMP   TIMESTAMP_TZ    NOT NULL,
    PING_LAT            FLOAT           NOT NULL,
    PING_LNG            FLOAT           NOT NULL,
    ACCURACY_M          FLOAT,
    ROUTE_ID            VARCHAR(64),
    DETECTION_METHOD    VARCHAR(80)     NOT NULL,
    DISTANCE_M          FLOAT
);

CREATE TABLE IF NOT EXISTS RESPONDER_LOCATION_PINGS (
    PING_ID             VARCHAR(36)     NOT NULL,
    RESPONDER_ID        VARCHAR(36)     NOT NULL,
    LAT                 FLOAT           NOT NULL,
    LNG                 FLOAT           NOT NULL,
    ACCURACY_M          FLOAT,
    TIMESTAMP           TIMESTAMP_TZ    NOT NULL,
    SPEED_MPS           FLOAT,
    HEADING             FLOAT,
    ASSIGNED_INCIDENT_ID VARCHAR(36),
    ROUTE_ID            VARCHAR(64),
    LEG_ID              VARCHAR(128)
);

CREATE DYNAMIC TABLE IF NOT EXISTS LIVE_RESOURCE_GAPS
    TARGET_LAG = '1 minute'
    WAREHOUSE = {{SNOWFLAKE_WAREHOUSE}}
    CLUSTER BY (SECTOR_ID, H3_RES8, COMPUTED_AT)
AS
WITH responder_h3 AS (
    SELECT
        TO_VARCHAR(H3_LATLNG_TO_CELL(LAT, LNG, 8)) AS H3_RES8,
        COUNT_IF(STATUS = 'idle') AS AVAILABLE_RESPONDERS
    FROM DISASTER_DB.CLEAN.RESPONDERS
    WHERE LAT IS NOT NULL
      AND LNG IS NOT NULL
    GROUP BY H3_RES8
),
open_area_clusters AS (
    SELECT
        CLUSTER_WINDOW_ID,
        H3_RES8,
        SECTOR_ID,
        WINDOW_END,
        OPEN_INCIDENTS,
        IMMEDIATE_COUNT,
        DELAYED_COUNT,
        MAX_PRIORITY_SCORE
    FROM DISASTER_DB.FEATURES.LIVE_H3_CLUSTER_WINDOWS
)
SELECT
    CLUSTER_WINDOW_ID AS GAP_ID,
    open_area_clusters.H3_RES8,
    SECTOR_ID,
    WINDOW_END AS COMPUTED_AT,
    OPEN_INCIDENTS,
    IMMEDIATE_COUNT,
    DELAYED_COUNT,
    COALESCE(responder_h3.AVAILABLE_RESPONDERS, 0) AS AVAILABLE_RESPONDERS,
    GREATEST(
        (IMMEDIATE_COUNT + DELAYED_COUNT) - COALESCE(responder_h3.AVAILABLE_RESPONDERS, 0),
        0
    ) AS GAP_SCORE,
    MAX_PRIORITY_SCORE,
    CASE
        WHEN GREATEST(
            (IMMEDIATE_COUNT + DELAYED_COUNT) - COALESCE(responder_h3.AVAILABLE_RESPONDERS, 0),
            0
        ) > 0 THEN 'Review nearby idle units and rerun route optimization.'
        ELSE 'Coverage acceptable. Continue monitoring.'
    END AS RECOMMENDATION
FROM open_area_clusters
LEFT JOIN responder_h3
  ON open_area_clusters.H3_RES8 = responder_h3.H3_RES8;

-- ═══════════════════════════════════════════════════════════════════════════
-- AGENT (command center / enrichment — DDL ready for future features)
-- ═══════════════════════════════════════════════════════════════════════════
USE SCHEMA AGENT;

CREATE TABLE IF NOT EXISTS CHAT_SESSIONS (
    SESSION_ID          VARCHAR(64)     NOT NULL,
    SCOPE               VARCHAR(32),
    SCOPE_REF_ID        VARCHAR(64),
    OPENED_BY           VARCHAR(64),
    OPENED_AT           TIMESTAMP_TZ    NOT NULL,
    CLOSED_AT           TIMESTAMP_TZ,
    TITLE               VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS CHAT_MESSAGES (
    MESSAGE_ID          VARCHAR(64)     NOT NULL,
    SESSION_ID          VARCHAR(64)     NOT NULL,
    SEQ                 NUMBER          NOT NULL,
    ROLE                VARCHAR(32)     NOT NULL,
    AGENT_NAME          VARCHAR(64),
    CONTENT             VARCHAR(16777216),
    TOOL_CALLS          VARIANT,
    CITATIONS           VARIANT,
    TOKENS              NUMBER,
    CREATED_AT          TIMESTAMP_TZ    NOT NULL
);

CREATE TABLE IF NOT EXISTS ENRICHED_INCIDENT_REPORTS (
    INCIDENT_ID         VARCHAR(36)     NOT NULL,
    ENRICHED_TEXT       VARCHAR(16777216),
    SEVERITY            VARCHAR(20),
    SECTOR_ID           VARCHAR(64),
    STATUS              VARCHAR(32),
    VICTIM_COUNT        NUMBER,
    H3_RES8             VARCHAR(32),
    TIMESTAMP           TIMESTAMP_TZ,
    EMBEDDING_MODEL     VARCHAR(64),
    UPDATED_AT          TIMESTAMP_TZ    NOT NULL
);

CREATE TABLE IF NOT EXISTS DISPATCH_DECISIONS (
    DECISION_ID         VARCHAR(64)     NOT NULL,
    RECOMMENDATION_ID   VARCHAR(64),
    INCIDENT_ID         VARCHAR(36),
    RESPONDER_USER_ID   VARCHAR(64),
    ACTION              VARCHAR(32)     NOT NULL,
    REASON              VARCHAR(500),
    OVERRIDE_PAYLOAD    VARIANT,
    DECIDED_AT          TIMESTAMP_TZ    NOT NULL,
    SESSION_ID          VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS FEEDBACK_LABELS (
    LABEL_ID            VARCHAR(64)     NOT NULL,
    INCIDENT_ID         VARCHAR(36),
    RECOMMENDATION_ID   VARCHAR(64),
    LABEL_TYPE          VARCHAR(32),
    LABEL_VALUE         VARCHAR(64),
    NOTES               VARCHAR(2000),
    LABELED_BY          VARCHAR(64),
    LABELED_AT          TIMESTAMP_TZ    NOT NULL
);

CREATE TABLE IF NOT EXISTS AGENT_RUNS (
    RUN_ID              VARCHAR(64)     NOT NULL,
    AGENT_NAME          VARCHAR(64)     NOT NULL,
    SESSION_ID          VARCHAR(64),
    INCIDENT_ID         VARCHAR(36),
    INPUT_PAYLOAD       VARIANT,
    OUTPUT_PAYLOAD      VARIANT,
    TOOL_CALLS          VARIANT,
    CORTEX_SEARCH_HITS  VARIANT,
    STARTED_AT          TIMESTAMP_TZ    NOT NULL,
    ENDED_AT            TIMESTAMP_TZ,
    LATENCY_MS          NUMBER,
    COST_USD            FLOAT,
    ERROR               VARCHAR(2000)
);

-- ── Migrate existing CLEAN.INCIDENTS (CREATE IF NOT EXISTS does not add columns) ──
USE SCHEMA CLEAN;
ALTER TABLE INCIDENTS ADD COLUMN IF NOT EXISTS SUBMISSION_ID VARCHAR(64);
ALTER TABLE INCIDENTS ADD COLUMN IF NOT EXISTS SEVERITY VARCHAR(20);
ALTER TABLE INCIDENTS ADD COLUMN IF NOT EXISTS INCIDENT_DESCRIPTION VARCHAR(500);
ALTER TABLE INCIDENTS ADD COLUMN IF NOT EXISTS SIM_RUN_ID VARCHAR(64);
ALTER TABLE INCIDENTS ADD COLUMN IF NOT EXISTS FIRST_REPORTED_AT TIMESTAMP_TZ;
ALTER TABLE INCIDENTS ADD COLUMN IF NOT EXISTS LAST_UPDATED_AT TIMESTAMP_TZ;

-- Align VICTIMS array columns if an older VARCHAR definition exists (no-op if already ARRAY).
-- If migration fails, recreate VICTIMS from the CREATE TABLE above in Snowsight.

-- Verify
SHOW SCHEMAS IN DATABASE DISASTER_DB;
SHOW TABLES IN SCHEMA DISASTER_DB.RAW;
SHOW TABLES IN SCHEMA DISASTER_DB.CLEAN;
SHOW TABLES IN SCHEMA DISASTER_DB.SERVING;
SHOW DYNAMIC TABLES IN SCHEMA DISASTER_DB.GEO;
SHOW DYNAMIC TABLES IN SCHEMA DISASTER_DB.FEATURES;
SHOW DYNAMIC TABLES IN SCHEMA DISASTER_DB.SERVING;
